[package]
name = "sudokugen"
description = """
sudokugen is a Sudoku (9x9) puzzle generator and solver crate.
"""
version = "0.1.0"
authors = ["Jani Suihko <janigbg@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
rand_pcg = "0.1"
log = "0.4"
env_logger = "0.6"
